version: 2.1

_run:
  jceinstall: &jceinstall
    name: "Download JCE unlimited strength policy to allow the 256 bit keys"
    command: |
      curl -L --cookie 'oraclelicense=accept-securebackup-cookie;'  http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip -o /tmp/jce_policy.zip
      unzip -o /tmp/jce_policy.zip -d /tmp
      sudo mv -f /tmp/UnlimitedJCEPolicyJDK8/US_export_policy.jar $JAVA_HOME/jre/lib/security/US_export_policy.jar
      sudo mv -f /tmp/UnlimitedJCEPolicyJDK8/local_policy.jar $JAVA_HOME/jre/lib/security/local_policy.jar
  javaversion: &javaversion
    name: "Report Java JDK Version being used"
    command: |
      echo ${JAVA_HOME}
  restorecache: &restorecache
    name: "Download and Cache Dependencies"
    keys:
      - v1-dependencies-{{ checksum "pom.xml" }}
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-

jobs:
  build-and-test:
    docker:
      - image: maven:3.9.9-eclipse-temurin-22-alpine
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Run tests
          command: mvn test
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

workflows:
  build-and-test:
    jobs:
      - build-and-test